### ISSUE TITLE
Why "config.name must be identical to the resource name" ?

### ISSUE THREAD

**Issue by donemtrimbur** [Mongey/terraform-provider-kafka-connect#146]
There is currently a constraint hard coded in the provider that required the config.name to be the same as the resource name : 

https://github.com/Mongey/terraform-provider-kafka-connect/blob/master/connect/resource_kafka_connector.go#L60

This prevents using dynamic resource creation with for_each and/or modules

```hcl
module "kafka_connect_connector_done_platform" {
  source        = "./modules/kafka/connect/connector"
  name          = "done-platform-sink"
  config        = {
    name = "" <---- no access to the resource name here
  }
  config_object = module.config.config_object
}
```

This produce the following error : 

```
│ Error: config.name must be identical to the resource name
│ 
│   with module.kafka_connect_connector_done_platform.kafka-connect_connector.main,
│   on modules/kafka/connect/connector/connector.tf line 1, in resource "kafka-connect_connector" "main":
│    1: resource "kafka-connect_connector" "main" {
│ 
```

What is the purpose of this constraint ? Could it be removed ?

**Comment by Mongey** [comment]
It has been a while since I've worked with Kafka Connect, I'm not sure why it's needed, maybe we can remove it.

**Comment by donemtrimbur** [comment]
Indeed you are right and I missread the code, it is not the name of the Terraform resource that should be the same but the config "name" property and the name of the connector. And this is indeed the expected behaviour by Kafka connect.

I'm closing the issue
