### ISSUE TITLE
How complete is this?

### ISSUE THREAD

**Issue by darrenhaken** [Mongey/terraform-provider-kafka-connect#2]
I was wondering how complete this is against the spec?

Does it support it support the full resource life cycle like GET, PUT, DELETE? 
I assume it must do if its TF :)

**Comment by Mongey** [comment]
👋  @darrenhaken,

> I was wondering how complete this is against the spec?

Which spec are your referring to? The provider doesn't attempt to do anything special with the actual config values, so we just pass the value of `config` along to the server -- so it's should be fully complete in that sense.

> Does it support it support the full resource life cycle like GET, PUT, DELETE?

Yep, all that should just work 🤞.

I'll create a v0.1.0 release and update the README with install instructions.

**Comment by Mongey** [comment]
🗣   I've released [`v0.1.0`](https://github.com/Mongey/terraform-provider-kafka-connect/releases/tag/v0.1.0). 🎉 

I'll close this for now, but feel free to open new issues if you run into any trouble, or there's something missing. 🙇
