### ISSUE TITLE
How to work with multiple connectors in tf file 

### ISSUE THREAD

**Issue by huyngopt1994** [Mongey/terraform-provider-kafka-connect#34]
Right now I see the provider only allows one to connect endpoint, the case is I had multiple connectors and want to manage them via a terraform module?

**Comment by Mongey** [comment]
You could leverage [terraform's provider aliasing function](https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-configurations)

**Comment by huyngopt1994** [comment]
@Mongey yes, It works thanks
