### ISSUE TITLE
Terraform 14 v0.2.2 hash issue

### ISSUE THREAD

**Issue by pbr0ck3r** [Mongey/terraform-provider-kafka-connect#38]
```
2021/02/09 19:43:33 [DEBUG] GET https://github.com/Mongey/terraform-provider-kafka-connect/releases/download/v0.2.2/terraform-provider-kafka-connect_0.2.2_SHA256SUMS
2021/02/09 19:43:33 [TRACE] HTTP client GET request to https://github.com/Mongey/terraform-provider-kafka-connect/releases/download/v0.2.2/terraform-provider-kafka-connect_0.2.2_SHA256SUMS

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Error: Failed to install provider

Error while installing mongey/kafka-connect v0.2.2: could not query provider
registry for registry.terraform.io/mongey/kafka-connect: failed to retrieve
authentication checksums for provider: 404 Not Found
```

The issue is that here on github the link is contains:
terraform-provider-kafka-connect_v0.2.2
on terraform it is trying to use:
terraform-provider-kafka-connect_0.2.2 (missing the v)

So terraform 14 is unable to verify the hash

**Comment by Mongey** [comment]
@pbr0ck3r I think I fixed this with the [v0.2.3](https://github.com/Mongey/terraform-provider-kafka-connect/releases/tag/v0.2.3) release, can you check it out?

**Comment by pbr0ck3r** [comment]
I tried running version v0.2.3 with terraform 14.5 and am running into the following issue:
```
2021/02/09 19:53:18 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/mongey/kafka-connect\"] (close)" is waiting for "module.s3_connect.kafka-connect_connector.this (expand)"
2021/02/09 19:53:18 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
2021/02/09 19:53:18 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "module.s3_connect.kafka-connect_connector.this (expand)"
2021/02/09 19:53:23 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "module.s3_connect.kafka-connect_connector.this (expand)"
2021/02/09 19:53:23 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
2021/02/09 19:53:23 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/mongey/kafka-connect\"] (close)" is waiting for "module.s3_connect.kafka-connect_connector.this (expand)"
2021/02/09 19:53:28 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/mongey/kafka-connect\"] (close)" is waiting for "module.s3_connect.kafka-connect_connector.this (expand)"
```

**Comment by pbr0ck3r** [comment]
Also yes the hash checking works with v0.2.3 just fine.

**Comment by hoanht140589** [comment]
I have the same issue with TF 14.8 on version 0.2.3, it keeps 
`2021/07/01 05:20:26 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "module.kafka (close)"
2021/07/01 05:20:26 [TRACE] dag/walk: vertex "module.kafka.provider[\"registry.terraform.io/mongey/kafka-connect\"].data (close)" is waiting for "module.kafka.kafka-connect_connector.data-connectors (expand)"
2021/07/01 05:20:26 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
2021/07/01 05:20:27 [TRACE] dag/walk: vertex "root" is waiting for "module.kafka.kafka-connect_connector.data-connectors[\"postgres-system_transaction\"]"
2021/07/01 05:20:27 [TRACE] dag/walk: vertex "module.kafka (close)" is waiting for "module.kafka.kafka-connect_connector.data-connectors (expand)"
2021/07/01 05:20:31 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "module.kafka (close)"
2021/07/01 05:20:31 [TRACE] dag/walk: vertex "module.kafka.provider[\"registry.terraform.io/mongey/kafka-connect\"].data (close)" is waiting for "module.kafka.kafka-connect_connector.data-connectors (expand)"
2021/07/01 05:20:31 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
2021/07/01 05:20:32 [TRACE] dag/walk: vertex "root" is waiting for "module.kafka.kafka-connect_connector.data-connectors[\"postgres-system_transaction\"]"
2021/07/01 05:20:32 [TRACE] dag/walk: vertex "module.kafka (close)" is waiting for "module.kafka.kafka-connect_connector.data-connectors (expand)"
2021/07/01 05:20:36 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "module.kafka (close)"
2021/07/01 05:20:36 [TRACE] dag/walk: vertex "module.kafka.provider[\"registry.terraform.io/mongey/kafka-connect\"].data (close)" is waiting for "module.kafka.kafka-connect_connector.data-connectors (expand)"
2021/07/01 05:20:36 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"`

**Comment by pbr0ck3r** [comment]
This has nothing to do with install the provider which this issue is about and has been fixed. Please refer to https://github.com/Mongey/terraform-provider-kafka-connect/issues/37

**Comment by pbr0ck3r** [comment]
I am running TF 1.0.3 and confirm v0.2.3 works just fine.
