### ISSUE TITLE
M1 support 

### ISSUE THREAD

**Issue by mlaforet** [Mongey/terraform-provider-kafka-connect#42]
Upgrade to GO 1.16 to enable the darwin_arm64 build to occur in the release pipeline.

I have a branch that does this upgrade however it looks like I don't have permission to create branches in this repository.

**Comment by Mongey** [comment]
@mlaforet you need to fork, and push the branch to your repo, and then create a PR from there.

**Comment by mlaforet** [comment]
Thanks for the tip @Mongey, I've added my PR [here](https://github.com/Mongey/terraform-provider-kafka-connect/pull/50)

**Comment by Mongey** [comment]
https://github.com/Mongey/terraform-provider-kafka-connect/releases/tag/v0.2.4
