### ISSUE TITLE
Ensure connect service is running before attempting to create connector

### ISSUE THREAD

**Issue by ashinohara** [Mongey/terraform-provider-kafka-connect#6]
I am working on terraforming both the connect service, as well as the connectors at the same time.  I have added a `depends_on`, but sometimes the service dos not respond for a couple of seconds.  This causes the `kafka-connect_connector` to fail with `Post http://host.docker.internal:8083/connectors: EOF`. 

If we add in a call to make sure that the connector service is available before trying to create, this could be resolved.  I have an initial implementation of this and will submit a pull request.

**Comment by Mongey** [comment]
Thanks! Closed with #7
