### ISSUE TITLE
I followed the ReadMe - Connector not getting created 

### ISSUE THREAD

**Issue by kjang1750** [Mongey/terraform-provider-kafka-connect#80]
I got the following issue. I executed all the commands. 

:terraform-provider-kafka-connect  2$ make build
go install
 :terraform-provider-kafka-connect  2$ make test
go test ./...
?       github.com/Mongey/terraform-provider-kafka-connect      [no test files]
ok      github.com/Mongey/terraform-provider-kafka-connect/connect      (cached)
 :terraform-provider-kafka-connect  2$ make testacc
KAFKA_CONNECT_URL=http://localhost:8083 TF_LOG=debug TF_ACC=1 go test ./... -v  -timeout 120m
?       github.com/Mongey/terraform-provider-kafka-connect      [no test files]
2022/06/16 17:43:25 [INFO] Creating Provider
2022/06/16 17:43:25 [INFO] Created provider: {map[basic_auth_password:0xc000154280 basic_auth_username:0xc000154140 url:0xc000154000] map[kafka-connect_connector:0xc000156000] map[] map[] 0x1774380 <nil> false <nil> }
=== RUN   TestProvider
2022/06/16 17:43:25 [INFO] Creating Provider
2022/06/16 17:43:25 [INFO] Created provider: {map[basic_auth_password:0xc000154a00 basic_auth_username:0xc0001548c0 url:0xc000154780] map[kafka-connect_connector:0xc0001560e0] map[] map[] 0x1774380 <nil> false <nil> }
--- PASS: TestProvider (0.00s)
=== RUN   TestAccConnectorConfigUpdate
2022/06/16 17:43:25 [INFO] Initializing KafkaConnect client
2022/06/16 17:43:26 [WARN] Previously configured provider being re-configured. This can cause issues in concurrent testing if the configurations are not equal.
2022/06/16 17:43:26 [INFO] Initializing KafkaConnect client
2022/06/16 17:43:26 [WARN] Previously configured provider being re-configured. This can cause issues in concurrent testing if the configurations are not equal.
2022/06/16 17:43:26 [INFO] Initializing KafkaConnect client
[INFO] Created the connector error code: 0 , message: 
2022/06/16 17:43:26 [INFO] Attempting to read remote data for connector sqlite-sink
2022/06/16 17:43:26 [INFO] Current local config nonsensitive values are: map[auto.create:true connection.url:jdbc:sqlite:test.db connector.class:io.confluent.connect.jdbc.JdbcSinkConnector name:sqlite-sink tasks.max:2 topics:orders]
2022/06/16 17:43:26 [INFO] Local config nonsensitive data updated to map[auto.create:true connection.url:jdbc:sqlite:test.db connector.class:io.confluent.connect.jdbc.JdbcSinkConnector name:sqlite-sink tasks.max:2 topics:orders]
2022/06/16 17:43:26 [WARN] Previously configured provider being re-configured. This can cause issues in concurrent testing if the configurations are not equal.
2022/06/16 17:43:26 [INFO] Initializing KafkaConnect client
2022/06/16 17:43:26 [WARN] Previously configured provider being re-configured. This can cause issues in concurrent testing if the configurations are not equal.
2022/06/16 17:43:26 [INFO] Initializing KafkaConnect client
2022/06/16 17:43:26 [INFO] Attempting to read remote data for connector sqlite-sink
2022/06/16 17:43:26 [INFO] Current local config nonsensitive values are: map[auto.create:true connection.url:jdbc:sqlite:test.db connector.class:io.confluent.connect.jdbc.JdbcSinkConnector name:sqlite-sink tasks.max:2 topics:orders]
2022/06/16 17:43:26 [INFO] Local config nonsensitive data updated to map[auto.create:true connection.url:jdbc:sqlite:test.db connector.class:io.confluent.connect.jdbc.JdbcSinkConnector name:sqlite-sink tasks.max:2 topics:orders]
2022/06/16 17:43:26 [WARN] Previously configured provider being re-configured. This can cause issues in concurrent testing if the configurations are not equal.
2022/06/16 17:43:26 [INFO] Initializing KafkaConnect client
2022/06/16 17:43:26 [WARN] Previously configured provider being re-configured. This can cause issues in concurrent testing if the configurations are not equal.
2022/06/16 17:43:26 [INFO] Initializing KafkaConnect client
2022/06/16 17:43:26 Import connector with name: sqlite-sink
2022/06/16 17:43:26 [INFO] Attempting to read remote data for connector sqlite-sink
2022/06/16 17:43:26 [INFO] Current local config nonsensitive values are: map[]
2022/06/16 17:43:26 [INFO] Local config nonsensitive data updated to map[auto.create:true connection.url:jdbc:sqlite:test.db connector.class:io.confluent.connect.jdbc.JdbcSinkConnector name:sqlite-sink tasks.max:2 topics:orders]
2022/06/16 17:43:26 [WARN] Previously configured provider being re-configured. This can cause issues in concurrent testing if the configurations are not equal.
2022/06/16 17:43:26 [INFO] Initializing KafkaConnect client
2022/06/16 17:43:26 [INFO] Attempting to read remote data for connector sqlite-sink
2022/06/16 17:43:26 [INFO] Current local config nonsensitive values are: map[auto.create:true connection.url:jdbc:sqlite:test.db connector.class:io.confluent.connect.jdbc.JdbcSinkConnector name:sqlite-sink tasks.max:2 topics:orders]
2022/06/16 17:43:26 [INFO] Local config nonsensitive data updated to map[auto.create:true connection.url:jdbc:sqlite:test.db connector.class:io.confluent.connect.jdbc.JdbcSinkConnector name:sqlite-sink tasks.max:2 topics:orders]
2022/06/16 17:43:26 [WARN] Previously configured provider being re-configured. This can cause issues in concurrent testing if the configurations are not equal.
2022/06/16 17:43:26 [INFO] Initializing KafkaConnect client
2022/06/16 17:43:26 [WARN] Previously configured provider being re-configured. This can cause issues in concurrent testing if the configurations are not equal.
2022/06/16 17:43:26 [INFO] Initializing KafkaConnect client
2022/06/16 17:43:26 [INFO] Requesting update to connector sqlite-sink
2022/06/16 17:43:26 [INFO] Looking for sqlite-sink
2022/06/16 17:43:27 [INFO] Local config nonsensitive updated to: map[auto.create:true connection.url:jdbc:sqlite:test.db connector.class:io.confluent.connect.jdbc.JdbcSinkConnector name:sqlite-sink tasks.max:1 topics:orders]
2022/06/16 17:43:27 [INFO] Attempting to read remote data for connector sqlite-sink
2022/06/16 17:43:27 [INFO] Current local config nonsensitive values are: map[auto.create:true connection.url:jdbc:sqlite:test.db connector.class:io.confluent.connect.jdbc.JdbcSinkConnector name:sqlite-sink tasks.max:1 topics:orders]
2022/06/16 17:43:27 [INFO] Local config nonsensitive data updated to map[auto.create:true connection.url:jdbc:sqlite:test.db connector.class:io.confluent.connect.jdbc.JdbcSinkConnector name:sqlite-sink tasks.max:1 topics:orders]
2022/06/16 17:43:27 [WARN] Previously configured provider being re-configured. This can cause issues in concurrent testing if the configurations are not equal.
2022/06/16 17:43:27 [INFO] Initializing KafkaConnect client
2022/06/16 17:43:27 [WARN] Previously configured provider being re-configured. This can cause issues in concurrent testing if the configurations are not equal.
2022/06/16 17:43:27 [INFO] Initializing KafkaConnect client
2022/06/16 17:43:27 [INFO] Attempting to read remote data for connector sqlite-sink
2022/06/16 17:43:27 [INFO] Current local config nonsensitive values are: map[auto.create:true connection.url:jdbc:sqlite:test.db connector.class:io.confluent.connect.jdbc.JdbcSinkConnector name:sqlite-sink tasks.max:1 topics:orders]
2022/06/16 17:43:27 [INFO] Local config nonsensitive data updated to map[auto.create:true connection.url:jdbc:sqlite:test.db connector.class:io.confluent.connect.jdbc.JdbcSinkConnector name:sqlite-sink tasks.max:1 topics:orders]
2022/06/16 17:43:27 [WARN] Previously configured provider being re-configured. This can cause issues in concurrent testing if the configurations are not equal.
2022/06/16 17:43:27 [INFO] Initializing KafkaConnect client
2022/06/16 17:43:27 [WARN] Previously configured provider being re-configured. This can cause issues in concurrent testing if the configurations are not equal.
2022/06/16 17:43:27 [INFO] Initializing KafkaConnect client
[INFO] Deleting the connector sqlite-sink
--- PASS: TestAccConnectorConfigUpdate (2.01s)
PASS
ok      github.com/Mongey/terraform-provider-kafka-connect/connect      (cached)

Unfortunately, I do not see the connector created. Am I doing something wrong?

**Comment by Mongey** [comment]
When running the tests, resources will be destroyed on test teardown
